codingchallenge/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

from codingchallenge import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^choose/$', views.choose, name='choose'),
    url(r'^(?P<category_id_1>[0-9]+)/(?P<category_id_2>[0-9]+)/(?P<category_id_3>[0-9]+)/(?P<page>[0-9]+)/$', views.results, name='results'),
)

eventbrite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^codingchallenge/', include('codingchallenge.urls', namespace='codingchallenge'))
)

codingchallenge/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    resource_uri = models.URLField()
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    name_localized = models.CharField(max_length=200)
    short_name = models.CharField(max_length=200)
    short_name_localized = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

codingchallenge/views.py
import requests

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from codingchallenge.models import Category
from codingchallenge.credentials import *


# Create your views here.
def index(request):
    categories = Category.objects.all()
    return render(request, "codingchallenge/index.html", {"categories": categories})


def choose(request):
    try:
        selected = request.GET.copy().pop('category')  # the GET request is immutable, so we must copy it to pop it
        if len(selected) != 3:
            raise KeyError

        # This is to catch users who try to manipulate the url to request a category that doesn't exist
        valid_categories = [str(category.id) for category in Category.objects.all()]
        for category in selected:
            if category not in valid_categories:
                raise NameError
    except KeyError:
        return render(request, "codingchallenge/index.html", {
            "error_message": "Please select exactly 3 categories",
            "categories": Category.objects.all(),
        })
    except NameError:
        return HttpResponse("Screw you, your sneaky tricks will not work on me")
    else:
        return HttpResponseRedirect(reverse("codingchallenge:results", args=(selected[0], selected[1], selected[2], 1)))


def results(request, category_id_1, category_id_2, category_id_3, page):
    r = requests.get("https://www.eventbriteapi.com/v3/events/search/?token=%s&categories=%s,%s,%s&page=%s" %
                     (TOKEN, category_id_1, category_id_2, category_id_3, page))
    events = r.json()["events"]
    page_info = r.json()["pagination"]
    context = {"category_id_1": category_id_1,
               "category_id_2": category_id_2,
               "category_id_3": category_id_3,
               "page_info": page_info,
               "events": events}
    return render(request, "codingchallenge/results.html", context)

codingchallenge/templates/codingchallenge/base.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>Eventbrite Coding Challenge - Jialin Ding</title>
    <link rel="stylesheet" type="text/css" href="{% static 'codingchallenge/style.css' %}" />
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

codingchallenge/templates/codingchallenge/index.html
{% extends "codingchallenge/base.html" %}

{% block content %}

<h1>Choose 3 Categories</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'codingchallenge:choose'%}" method="get">
{% csrf_token %}
{% for category in categories %}
    <input type="checkbox" name="category" id="choice{{ forloop.counter }}" value="{{ category.id }}" />
    <label for="choice{{ forloop.counter }}">{{ category.name }}</label><br />
{% endfor %}
<input type="submit" value="Choose" />
</form>

{% endblock %}

codingchallenge/templates/codingchallenge/page_links.html
{% load codingchallenge_extras %}

<a href="{% url 'codingchallenge:results' category_id_1 category_id_2 category_id_3 1 %}">First Page</a>

{% if page_info.page_number|sub_one > 0 %}
<a href="{% url 'codingchallenge:results' category_id_1 category_id_2 category_id_3 page_info.page_number|sub_one %}">Previous Page</a>
{% endif %}

{% if page_info.page_number|add_one <= page_info.page_count %}
<a href="{% url 'codingchallenge:results' category_id_1 category_id_2 category_id_3 page_info.page_number|add_one %}">Next Page</a>
{% endif %}

<a href="{% url 'codingchallenge:results' category_id_1 category_id_2 category_id_3 page_info.page_count %}">Last Page</a>

<a href="{% url 'codingchallenge:index' %}">Choose Again</a>

codingchallenge/templates/codingchallenge/results.html
{% extends "codingchallenge/base.html" %}
{% load codingchallenge_extras %}

{% block content %}

<h1>This is page {{page_info.page_number}} of {{page_info.page_count}} ({{page_info.page_size}} items per page, {{page_info.object_count}} items overall)</h1>

{% include "codingchallenge/page_links.html" %}

<ol start="{{ page_info|start_index }}">
{% for event in events %}
    <li>
    	<h3>{{ event.name.text }}</h3>
    	<ul>
    		<li><a href="{{ event.url }}">{{ event.url }}</a></li>
    		<li>{{ event.description.text }}</li>
    		<li>Location -- {{ event.venue.address.address_1 }} {{ event.venue.address.city }} {{ event.venue.address.region }} {{ event.venue.address.postal_code }} {{ event.venue.address.country }}</li>
    		<li>Time -- {{ event.start.local }} - {{ event.end.local }}</li>
    	</ul>
    </li>
{% endfor %}
</ol>

{% include "codingchallenge/page_links.html" %}

{% endblock %}